name: Validate Code

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v4
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Check code formatting
              run: |
                  pnpm run format
                  git diff --exit-code

            - name: Lint TypeScript
              run: pnpm run lint

            - name: Build TypeScript
              run: pnpm run build

            - name: Validate configuration structure
              run: |
                  # Check that example config is valid JSON
                  node -e "JSON.parse(require('fs').readFileSync('runners.config.example.json', 'utf8'))"
                  echo "✅ Example configuration is valid JSON"
